name: Discord Notification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Push Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"username": "GitHub Actions", "content": "**New Push Detected!**\nRepository: ${GITHUB_REPOSITORY}\nCommit: ${GITHUB_SHA}\nBranch: ${GITHUB_REF}"}' \
          ${https://discordapp.com/api/webhooks/1366341624044457984/Foglc-iwQVTM0pLPZ3Dihyxr0FeMFn4_sePRfSJN7U7hOeQuJHxd1n9-JTMwSy8wW1sw}
        env:
          DISCORD_WEBHOOK: ${{ secrets.https://discordapp.com/api/webhooks/1366341624044457984/Foglc-iwQVTM0pLPZ3Dihyxr0FeMFn4_sePRfSJN7U7hOeQuJHxd1n9-JTMwSy8wW1sw }}
