name: Discord Notification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Push Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"username": "GitHub Actions", "content": "**New Push Detected!**\nRepository: ${GITHUB_REPOSITORY}\nCommit: ${GITHUB_SHA}\nBranch: ${GITHUB_REF}"}' \
          ${DISCORD_WEBHOOK}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
